# Generated by Django 4.1.6 on 2023-02-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='products', verbose_name='Изображение'),
        ),
    ]
