# Generated by Django 4.1.6 on 2023-02-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_productitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='tag',
            field=models.CharField(default=1, max_length=20, unique='true', verbose_name='Тэг'),
            preserve_default=False,
        ),
    ]
