# Generated by Django 4.1.6 on 2023-02-16 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_menu_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.menu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='sub_menu',
            field=models.BooleanField(default=False),
        ),
    ]
