# Generated by Django 4.1.6 on 2023-03-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_menu_parent_menu_sub_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='tag',
            field=models.CharField(blank=True, default='123', max_length=20, unique=True, verbose_name='Тэг'),
        ),
    ]
