# Generated by Django 4.1.6 on 2023-03-17 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_menu_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='tag',
        ),
    ]
