# Generated by Django 4.1.6 on 2023-03-17 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_menu_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='parent',
            new_name='parents',
        ),
    ]
