# Generated by Django 4.1.6 on 2023-03-17 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_rename_parent_menu_parents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='parents',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='sub_menu',
        ),
    ]
