# Generated by Django 4.1.6 on 2023-03-17 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_menu_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productitem',
            old_name='image',
            new_name='img',
        ),
    ]
