# Generated by Django 4.1.6 on 2023-03-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_rename_image_productitem_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='url_name',
            field=models.CharField(default=123, max_length=50, verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
