# Generated by Django 4.1.6 on 2023-03-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_menu_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='url_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Ссылка'),
        ),
    ]
