# Generated by Django 4.1.6 on 2023-03-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_products_delete_productitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='desript',
            field=models.CharField(blank=True, max_length=5000, verbose_name='Описание'),
        ),
    ]
